import type { Cartridge } from '../types/cartridge'

/** Known westkitty GitHub Pages playables + factory Make tool — https launch / safe script only. */
const FLEET: Omit<
  Cartridge,
  'favorite' | 'recentRank' | 'duplicateOf' | 'git' | 'missing' | 'broken' | 'manifestErrors' | 'manifestWarnings' | 'source'
>[] = [
  {
    id: 'factory-workbench',
    title: 'Make — 2D Game Factory Workbench',
    description:
      'Create / Remix / Pack 2D games in the factory workbench. Safe launch: copies npm instructions (npm run app / npm run app:dev). Arcade shell stays; make-backend is swappable (2D factory now, 3D later). After pack+Pages publish, carts land via fleetPages seed or discovery of weaselworks.json under games/demos/proofs.',
    projectType: 'utility',
    status: 'TOOL',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory',
    launch: { method: 'script', scriptId: 'npm-dev' },
    platforms: ['web'],
    tags: ['factory', 'make', 'tool', 'workbench', 'create', 'remix', 'pack'],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'deeper',
    title: 'Deeper',
    description: 'Deeper on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/Deeper',
    launch: { method: 'url', url: 'https://westkitty.github.io/Deeper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Deeper' },
  },
  {
    id: 'starsilk-pwa-mapper',
    title: 'Starsilk PWA Mapper',
    description: 'Starsilk PWA Mapper on GitHub Pages.',
    projectType: 'app',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Starsilk_PWA_Mapper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'pwa', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Starsilk_PWA_Mapper' },
  },
  {
    id: 'c-chase',
    title: 'C Chase',
    description: 'c_chase on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/c_chase/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/c_chase' },
  },
  {
    id: 'flitdice',
    title: 'Flitdice',
    description: 'flitdice on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/flitdice/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/flitdice' },
  },
  {
    id: 'flit-doll',
    title: 'Flit Doll',
    description: 'Flit_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Doll' },
  },
  {
    id: 'flit-substitute-doll',
    title: 'Flit Substitute Doll',
    description: 'Flit_Substitute_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Doll' },
  },
  {
    id: 'flit-substitute-fey',
    title: 'Flit Substitute Fey',
    description: 'Flit_Substitute_Fey on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Fey/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Fey' },
  },
  {
    id: 'dndex',
    title: 'DnDex',
    description: 'DnDex on GitHub Pages.',
    projectType: 'app',
    status: 'TOOL',
    launch: { method: 'url', url: 'https://westkitty.github.io/DnDex/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'tool', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/DnDex' },
  },
  {
    id: 'the-full-weasel',
    title: 'The Full Weasel',
    description: 'The_Full_Weasel on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/The_Full_Weasel/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/The_Full_Weasel' },
  },
  {
    id: "action-roguelite",
    title: "Action Roguelite",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/action-roguelite",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/action-roguelite/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "boss-rush",
    title: "Boss Rush",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/boss-rush",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/boss-rush/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "breakout",
    title: "Breakout",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/breakout",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/breakout/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "bullet-hell",
    title: "Bullet Hell",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/bullet-hell",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/bullet-hell/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "chase-platformer",
    title: "Chase Platformer",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/chase-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/chase-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "climbing-game",
    title: "Climbing Game",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/climbing-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/climbing-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "collectathon-platformer",
    title: "Collectathon Platformer",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/collectathon-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/collectathon-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "colony-lite",
    title: "Colony Lite",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/colony-lite",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/colony-lite/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "dungeon-crawler",
    title: "Dungeon Crawler",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/dungeon-crawler",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/dungeon-crawler/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "endless-runner",
    title: "Endless Runner",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/endless-runner",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/endless-runner/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "exploration-game",
    title: "Exploration Game",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/exploration-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/exploration-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "gallery-shooter",
    title: "Gallery Shooter",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/gallery-shooter",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/gallery-shooter/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "grappling-platformer",
    title: "Grappling Platformer",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/grappling-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/grappling-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "idle-incremental",
    title: "Idle Incremental",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/idle-incremental",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/idle-incremental/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "lane-defense",
    title: "Lane Defense",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/lane-defense",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/lane-defense/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "local-party-game",
    title: "Local Party Game",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/local-party-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/local-party-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "metroidvania",
    title: "Metroidvania",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/metroidvania",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/metroidvania/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "pet-creature",
    title: "Pet Creature",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/pet-creature",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/pet-creature/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "physics-toy",
    title: "Physics Toy",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/physics-toy",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/physics-toy/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "point-and-click",
    title: "Point And Click",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/point-and-click",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/point-and-click/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "pong",
    title: "Pong",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/pong",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/pong/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "precision-platformer",
    title: "Precision Platformer",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/precision-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/precision-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "puzzle-platformer",
    title: "Puzzle Platformer",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/puzzle-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/puzzle-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "qa-image-game",
    title: "Qa Image Game",
    description: "2D Game Factory qa on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-image-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/qa-image-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "qa", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "qa-provenance-game",
    title: "Qa Provenance Game",
    description: "2D Game Factory qa on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-provenance-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/qa-provenance-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "qa", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "reaction-timing",
    title: "Reaction Timing",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/reaction-timing",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/reaction-timing/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "rhythm-action",
    title: "Rhythm Action",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/rhythm-action",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/rhythm-action/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "run-and-gun",
    title: "Run And Gun",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/run-and-gun",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/run-and-gun/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "shopkeeper",
    title: "Shopkeeper",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/shopkeeper",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/shopkeeper/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "simple-rts",
    title: "Simple Rts",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/simple-rts",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/simple-rts/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "sokoban",
    title: "Sokoban",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/sokoban",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/sokoban/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "starter",
    title: "Starter",
    description: "2D Game Factory starter on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/starter",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/starter/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "starter", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "stealth-game",
    title: "Stealth Game",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/stealth-game",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/stealth-game/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "survivor-like",
    title: "Survivor Like",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/survivor-like",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/survivor-like/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "time-trial-racer",
    title: "Time Trial Racer",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/time-trial-racer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/time-trial-racer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "top-down-adventure",
    title: "Top Down Adventure",
    description: "2D Game Factory proof on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/proofs/top-down-adventure",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/top-down-adventure/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "proof", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "top-down-racer",
    title: "Top Down Racer",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/top-down-racer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/top-down-racer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "tower-defense",
    title: "Tower Defense",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/tower-defense",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/tower-defense/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "traditional-platformer",
    title: "Traditional Platformer",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/traditional-platformer",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/traditional-platformer/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "turn-based-tactics",
    title: "Turn Based Tactics",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/turn-based-tactics",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/turn-based-tactics/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "twin-stick-shooter",
    title: "Twin Stick Shooter",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/twin-stick-shooter",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/twin-stick-shooter/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: "visual-novel",
    title: "Visual Novel",
    description: "2D Game Factory demo on GitHub Pages.",
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: "/Users/andrew/2d_game_factory/2d_Game_Factory/demos/visual-novel",
    launch: { method: 'url', url: "https://westkitty.github.io/2d_Game_Factory/visual-novel/" },
    platforms: ['web'],
    tags: ["pages", "factory", "playable", "demo", "phaser"],
    lastActivity: '2026-09-17T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  }
]

export function loadFleetPagesLibrary(): Cartridge[] {
  return FLEET.map((c) => ({
    ...c,
    source: 'manual' as const,
    favorite: false,
    recentRank: undefined,
    missing: false,
    broken: false,
    manifestErrors: [],
    manifestWarnings: [],
  }))
}
