import type { Cartridge } from '../types/cartridge'

/** Known westkitty GitHub Pages playables — https launch only (no shell). */
const FLEET: Omit<
  Cartridge,
  'favorite' | 'recentRank' | 'duplicateOf' | 'git' | 'missing' | 'broken' | 'manifestErrors' | 'manifestWarnings' | 'source'
>[] = [
  {
    id: 'deeper',
    title: 'Deeper',
    description: 'Deeper on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/Deeper',
    launch: { method: 'url', url: 'https://westkitty.github.io/Deeper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Deeper' },
  },
  {
    id: 'starsilk-pwa-mapper',
    title: 'Starsilk PWA Mapper',
    description: 'Starsilk PWA Mapper on GitHub Pages.',
    projectType: 'app',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Starsilk_PWA_Mapper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'pwa', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Starsilk_PWA_Mapper' },
  },
  {
    id: 'qa-image-game',
    title: 'QA Image Game',
    description: '2D Game Factory pack on Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-image-game',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/qa-image-game/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'phaser', 'playable'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'qa-provenance-game',
    title: 'QA Provenance Game',
    description: '2D Game Factory pack on Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-provenance-game',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/qa-provenance-game/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'phaser', 'playable'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'c-chase',
    title: 'C Chase',
    description: 'c_chase on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/c_chase/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/c_chase' },
  },
  {
    id: 'flitdice',
    title: 'Flitdice',
    description: 'flitdice on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/flitdice/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/flitdice' },
  },
  {
    id: 'flit-doll',
    title: 'Flit Doll',
    description: 'Flit_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Doll' },
  },
  {
    id: 'flit-substitute-doll',
    title: 'Flit Substitute Doll',
    description: 'Flit_Substitute_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Doll' },
  },
  {
    id: 'flit-substitute-fey',
    title: 'Flit Substitute Fey',
    description: 'Flit_Substitute_Fey on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Fey/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Fey' },
  },
  {
    id: 'dndex',
    title: 'DnDex',
    description: 'DnDex on GitHub Pages.',
    projectType: 'app',
    status: 'TOOL',
    launch: { method: 'url', url: 'https://westkitty.github.io/DnDex/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'tool', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/DnDex' },
  },
  {
    id: 'the-full-weasel',
    title: 'The Full Weasel',
    description: 'The_Full_Weasel on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/The_Full_Weasel/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/The_Full_Weasel' },
  },
]

export function loadFleetPagesLibrary(): Cartridge[] {
  return FLEET.map((c) => ({
    ...c,
    source: 'manual' as const,
    favorite: false,
    recentRank: undefined,
    missing: false,
    broken: false,
    manifestErrors: [],
    manifestWarnings: [],
  }))
}
