import type { Cartridge } from '../types/cartridge'

/** Known westkitty GitHub Pages playables — https launch only (no shell). */
const FLEET: Omit<
  Cartridge,
  'favorite' | 'recentRank' | 'duplicateOf' | 'git' | 'missing' | 'broken' | 'manifestErrors' | 'manifestWarnings' | 'source'
>[] = [
  {
    id: 'deeper',
    title: 'Deeper',
    description: 'Deeper on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/Deeper',
    launch: { method: 'url', url: 'https://westkitty.github.io/Deeper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Deeper' },
  },
  {
    id: 'starsilk-pwa-mapper',
    title: 'Starsilk PWA Mapper',
    description: 'Starsilk PWA Mapper on GitHub Pages.',
    projectType: 'app',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Starsilk_PWA_Mapper/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'pwa', 'legacy-pages'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/Starsilk_PWA_Mapper' },
  },
  {
    id: 'qa-image-game',
    title: 'QA Image Game',
    description: '2D Game Factory pack on Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-image-game',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/qa-image-game/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'phaser', 'playable'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'qa-provenance-game',
    title: 'QA Provenance Game',
    description: '2D Game Factory pack on Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/games/qa-provenance-game',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/qa-provenance-game/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'phaser', 'playable'],
    lastActivity: '2026-09-14T14:30:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'c-chase',
    title: 'C Chase',
    description: 'c_chase on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/c_chase/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/c_chase' },
  },
  {
    id: 'flitdice',
    title: 'Flitdice',
    description: 'flitdice on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/flitdice/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/flitdice' },
  },
  {
    id: 'flit-doll',
    title: 'Flit Doll',
    description: 'Flit_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Doll' },
  },
  {
    id: 'flit-substitute-doll',
    title: 'Flit Substitute Doll',
    description: 'Flit_Substitute_Doll on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Doll/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Doll' },
  },
  {
    id: 'flit-substitute-fey',
    title: 'Flit Substitute Fey',
    description: 'Flit_Substitute_Fey on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/Flit_Substitute_Fey/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/Flit_Substitute_Fey' },
  },
  {
    id: 'dndex',
    title: 'DnDex',
    description: 'DnDex on GitHub Pages.',
    projectType: 'app',
    status: 'TOOL',
    launch: { method: 'url', url: 'https://westkitty.github.io/DnDex/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'tool', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/DnDex' },
  },
  {
    id: 'the-full-weasel',
    title: 'The Full Weasel',
    description: 'The_Full_Weasel on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    launch: { method: 'url', url: 'https://westkitty.github.io/The_Full_Weasel/' },
    platforms: ['web'],
    tags: ['pages', 'fleet', 'playable', 'legacy-pages'],
    repo: { url: 'https://github.com/westkitty/The_Full_Weasel' },
  },
  {
    id: 'bullet-hell',
    title: 'Bullet Hell',
    description: 'Factory genre demo (bullet-hell) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/bullet-hell',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/bullet-hell/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'chase-platformer',
    title: 'Chase Platformer',
    description: 'Factory genre demo (chase-platformer) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/chase-platformer',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/chase-platformer/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'idle-incremental',
    title: 'Idle Incremental',
    description: 'Factory genre demo (idle-incremental) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/idle-incremental',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/idle-incremental/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'metroidvania',
    title: 'Metroidvania',
    description: 'Factory genre demo (metroidvania) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/metroidvania',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/metroidvania/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'sokoban',
    title: 'Sokoban',
    description: 'Factory genre demo (sokoban) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/sokoban',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/sokoban/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'stealth-game',
    title: 'Stealth Game',
    description: 'Factory genre demo (stealth-game) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/stealth-game',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/stealth-game/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'top-down-racer',
    title: 'Top Down Racer',
    description: 'Factory genre demo (top-down-racer) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/top-down-racer',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/top-down-racer/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'tower-defense',
    title: 'Tower Defense',
    description: 'Factory genre demo (tower-defense) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/tower-defense',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/tower-defense/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'traditional-platformer',
    title: 'Traditional Platformer',
    description: 'Factory genre demo (traditional-platformer) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/traditional-platformer',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/traditional-platformer/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'turn-based-tactics',
    title: 'Turn Based Tactics',
    description: 'Factory genre demo (turn-based-tactics) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/turn-based-tactics',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/turn-based-tactics/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'twin-stick-shooter',
    title: 'Twin Stick Shooter',
    description: 'Factory genre demo (twin-stick-shooter) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/twin-stick-shooter',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/twin-stick-shooter/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
  {
    id: 'visual-novel',
    title: 'Visual Novel',
    description: 'Factory genre demo (visual-novel) on GitHub Pages.',
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/andrew/2d_game_factory/2d_Game_Factory/demos/visual-novel',
    launch: { method: 'url', url: 'https://westkitty.github.io/2d_Game_Factory/visual-novel/' },
    platforms: ['web'],
    tags: ['pages', 'factory', 'demo', 'playable', 'phaser'],
    lastActivity: '2026-09-15T00:00:00.000Z',
    repo: { url: 'https://github.com/westkitty/2d_Game_Factory' },
  },
]

export function loadFleetPagesLibrary(): Cartridge[] {
  return FLEET.map((c) => ({
    ...c,
    source: 'manual' as const,
    favorite: false,
    recentRank: undefined,
    missing: false,
    broken: false,
    manifestErrors: [],
    manifestWarnings: [],
  }))
}
