import type { Cartridge } from '../types/cartridge'
import { DEMO_GIT } from '../git/fixtures'

const DEXTER_ART = '/dexter/stinkweasel-dexter.png'

/** ≥12 synthetic cartridges for demo mode (zero filesystem access). */
export const DEMO_CARTRIDGES: Cartridge[] = [
  {
    id: 'demo-nebula-raiders',
    title: 'Nebula Raiders',
    description: 'Twin-stick asteroid brawler. Localhost Vite game.',
    artwork: undefined,
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/demo/Projects/nebula-raiders',
    launch: { method: 'localhost', url: 'http://localhost:5173' },
    platforms: ['web', 'mac'],
    tags: ['arcade', 'action', 'vite'],
    lastActivity: '2026-09-10T18:22:00.000Z',
    repo: { url: 'https://github.com/example/nebula-raiders' },
    source: 'demo',
    git: DEMO_GIT['demo-nebula-raiders'],
  },
  {
    id: 'demo-pixel-ledger',
    title: 'Pixel Ledger',
    description: 'Personal finance tracker with chunky pixel charts.',
    projectType: 'app',
    status: 'TOOL',
    localPath: '/Users/demo/Projects/pixel-ledger',
    launch: { method: 'script', scriptId: 'npm-dev' },
    platforms: ['web'],
    tags: ['finance', 'tool', 'charts'],
    lastActivity: '2026-09-12T09:01:00.000Z',
    source: 'demo',
    git: DEMO_GIT['demo-pixel-ledger'],
  },
  {
    id: 'demo-stinkweasel-simulator',
    title: 'Stinkweasel Simulator',
    description:
      'A lovingly grumpy tricolor dog sim — named after Dexter, the Weaselworks mascot.',
    artwork: DEXTER_ART,
    projectType: 'game',
    status: 'PLAYABLE',
    localPath: '/Users/demo/Projects/stinkweasel-sim',
    launch: { method: 'localhost', url: 'http://127.0.0.1:4173' },
    platforms: ['web', 'mac'],
    tags: ['dexter', 'mascot', 'sim', 'arcade'],
    lastActivity: '2026-09-13T14:00:00.000Z',
    source: 'demo',
    git: DEMO_GIT['demo-stinkweasel-simulator'],
  },
  {
    id: 'demo-fog-lab',
    title: 'Fog Lab',
    description: 'Procedural weather sketches and shader toys.',
    projectType: 'experiment',
    status: 'EXPERIMENT',
    localPath: '/Users/demo/Projects/fog-lab',
    launch: { method: 'html', htmlPath: 'index.html' },
    platforms: ['web'],
    tags: ['shaders', 'creative'],
    lastActivity: '2026-07-01T10:00:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-garden-bot',
    title: 'Garden Bot',
    description: 'WIP watering schedule helper. Still under construction.',
    projectType: 'utility',
    status: 'DEVELOPMENT',
    localPath: '/Users/demo/Projects/garden-bot',
    launch: { method: 'directory' },
    platforms: ['mac', 'web'],
    tags: ['utility', 'wip'],
    lastActivity: '2026-08-20T11:11:00.000Z',
    source: 'demo',
    git: DEMO_GIT['demo-garden-bot'],
  },
  {
    id: 'demo-cassette-clock',
    title: 'Cassette Clock',
    description: 'Retro desk clock — dormant since last winter.',
    projectType: 'app',
    status: 'DORMANT',
    localPath: '/Users/demo/Projects/cassette-clock',
    launch: { method: 'html', htmlPath: 'clock.html' },
    platforms: ['web'],
    tags: ['clock', 'retro'],
    lastActivity: '2025-12-02T08:00:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-broken-cart',
    title: 'Broken Cart (malformed demo)',
    description: 'Exercises broken-manifest reporting in the library UI.',
    projectType: 'app',
    status: 'BROKEN',
    localPath: '/Users/demo/Projects/broken-cart',
    launch: { method: 'directory' },
    platforms: [],
    tags: ['broken-manifest', 'qa'],
    lastActivity: '2026-06-15T12:00:00.000Z',
    source: 'demo',
    manifestIssues: [
      'Malformed JSON: Unexpected token',
      'Missing schemaVersion',
    ],
    git: DEMO_GIT['demo-broken-cart'],
  },
  {
    id: 'demo-missing-path',
    title: 'Ghost Directory',
    description: 'Registered path no longer exists — missing-project detection.',
    projectType: 'utility',
    status: 'BROKEN',
    localPath: '/Users/demo/Projects/does-not-exist',
    launch: { method: 'directory' },
    platforms: ['mac'],
    tags: ['missing', 'qa'],
    lastActivity: '2026-05-01T00:00:00.000Z',
    source: 'demo',
    missing: true,
    git: DEMO_GIT['demo-missing-path'],
  },
  {
    id: 'demo-archive-vault',
    title: 'Archive Vault',
    description: 'Old file indexer, kept for nostalgia.',
    projectType: 'utility',
    status: 'ARCHIVED',
    localPath: '/Users/demo/Projects/archive-vault',
    launch: { method: 'directory' },
    platforms: ['mac'],
    tags: ['archive', 'files'],
    lastActivity: '2024-11-11T11:11:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-hex-painter',
    title: 'Hex Painter',
    description: 'Tile map doodler for weekend RPG maps.',
    artwork: DEXTER_ART,
    projectType: 'utility',
    status: 'TOOL',
    localPath: '/Users/demo/Projects/hex-painter',
    launch: { method: 'localhost', url: 'http://localhost:3000' },
    platforms: ['web', 'windows', 'mac'],
    tags: ['art', 'maps', 'dexter'],
    lastActivity: '2026-09-08T16:40:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-pulse-metronome',
    title: 'Pulse Metronome',
    description: 'Click-track utility with MIDI out experiments.',
    projectType: 'utility',
    status: 'EXPERIMENT',
    localPath: '/Users/demo/Projects/pulse-metronome',
    launch: { method: 'script', scriptId: 'npm-start' },
    platforms: ['mac', 'web'],
    tags: ['audio', 'midi'],
    lastActivity: '2026-09-05T20:00:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-quest-notes',
    title: 'Quest Notes',
    description: 'Campaign journal for tabletop nights.',
    projectType: 'app',
    status: 'PLAYABLE',
    localPath: '/Users/demo/Projects/quest-notes',
    launch: { method: 'localhost', url: 'http://localhost:8080' },
    platforms: ['web'],
    tags: ['notes', 'ttrpg'],
    lastActivity: '2026-09-11T22:15:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-rail-yard',
    title: 'Rail Yard',
    description: 'Tiny train shunting puzzle — still wiring levels.',
    projectType: 'game',
    status: 'DEVELOPMENT',
    localPath: '/Users/demo/Projects/rail-yard',
    launch: { method: 'script', scriptId: 'npm-dev' },
    platforms: ['web', 'linux'],
    tags: ['puzzle', 'trains'],
    lastActivity: '2026-09-09T07:30:00.000Z',
    source: 'demo',
  },
  {
    id: 'demo-dexter-stickers',
    title: 'Dexter Sticker Sheet',
    description: 'Expression reference browser for Stinkweasel Dexter branding.',
    artwork: DEXTER_ART,
    projectType: 'utility',
    status: 'TOOL',
    localPath: '/Users/demo/Projects/dexter-stickers',
    launch: { method: 'html', htmlPath: 'sheet.html' },
    platforms: ['web', 'mac'],
    tags: ['dexter', 'art', 'branding'],
    lastActivity: '2026-09-14T10:00:00.000Z',
    source: 'demo',
  },
]

export function getDemoCartridges(): Cartridge[] {
  return DEMO_CARTRIDGES.map((c) => ({ ...c, tags: [...c.tags], platforms: [...c.platforms] }))
}
